# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestItemFree():
  def setup_method(self, method):
    self.driver = webdriver.Chrome('drivers/chrome/94/chromedriver.exe')
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_itemFree(self):
    self.driver.get("https://iterasys.com.br/plataforma/home/index.php?action=initial")
    self.driver.set_window_size(945, 999)
    self.driver.find_element(By.ID, "searchtext").click()
    self.driver.find_element(By.ID, "searchtext").send_keys("python")
    self.driver.find_element(By.ID, "btn_form_search").click()
    self.driver.find_element(By.CSS_SELECTOR, ".acessar").click()
    self.driver.find_element(By.CSS_SELECTOR, "#cadastro-rapido .modal-title").click()
    wait = WebDriverWait(self.driver, 3)
    assert self.driver.find_element(By.CSS_SELECTOR, "#cadastro-rapido .modal-title").text == "Cadastro Rápido"
    assert self.driver.find_element(By.ID, "btn_form_cad_cr").text == "Cadastre-se"
  
